export const pdfDataMap: Record<string, any> = {
    "John_Patient_details.pdf": {
      patientName: "John Doe",
      patientId: "P123456",
      hospitalName: "City Hospital",
      diagnosis: "Appendicitis",
      diagnosisCode: "K35.80",
      treatmentDetails: "Appendectomy surgery performed",
      claimAmount: 15000,
      serviceDate: "2023-06-15",
      confidence: {
        patientName: 0.98,
        patientId: 0.95,
        hospitalName: 0.93,
        diagnosis: 0.96,
        diagnosisCode: 0.92,
        treatmentDetails: 0.94,
        claimAmount: 0.97,
        serviceDate: 0.95,
      },
    },
    "Jane_Patient_details.pdf": {
      patientName: "Jane Smith",
      patientId: "P654321",
      hospitalName: "Metro Health Center",
      diagnosis: "Fractured Arm",
      diagnosisCode: "S52.501A",
      treatmentDetails: "X-ray and cast application",
      claimAmount: 7000,
      serviceDate: "2023-07-10",
      confidence: {
        patientName: 0.97,
        patientId: 0.94,
        hospitalName: 0.90,
        diagnosis: 0.93,
        diagnosisCode: 0.91,
        treatmentDetails: 0.95,
        claimAmount: 0.96,
        serviceDate: 0.92,
      },
    },
    "Alice_Patient_details.pdf": {
      patientName: "Alice Johnson",
      patientId: "P112233",
      hospitalName: "Sunrise Medical",
      diagnosis: "Gallstones",
      diagnosisCode: "K80.20",
      treatmentDetails: "Laparoscopic cholecystectomy",
      claimAmount: 22000,
      serviceDate: "2023-08-05",
      confidence: {
        patientName: 0.96,
        patientId: 0.93,
        hospitalName: 0.89,
        diagnosis: 0.95,
        diagnosisCode: 0.90,
        treatmentDetails: 0.94,
        claimAmount: 0.98,
        serviceDate: 0.91,
      },
    },
    "Robert_Patient_details.pdf": {
      patientName: "Robert Brown",
      patientId: "P778899",
      hospitalName: "Lakeside Hospital",
      diagnosis: "Migraine",
      diagnosisCode: "G43.909",
      treatmentDetails: "MRI and medication",
      claimAmount: 4500,
      serviceDate: "2023-09-01",
      confidence: {
        patientName: 0.99,
        patientId: 0.96,
        hospitalName: 0.94,
        diagnosis: 0.92,
        diagnosisCode: 0.91,
        treatmentDetails: 0.95,
        claimAmount: 0.97,
        serviceDate: 0.93,
      },
    },
    "Emily_Patient_details.pdf": {
      patientName: "Emily Davis",
      patientId: "P998877",
      hospitalName: "Green Valley Clinic",
      diagnosis: "Asthma",
      diagnosisCode: "J45.909",
      treatmentDetails: "Nebulizer therapy and medication",
      claimAmount: 3000,
      serviceDate: "2023-09-20",
      confidence: {
        patientName: 0.97,
        patientId: 0.95,
        hospitalName: 0.93,
        diagnosis: 0.94,
        diagnosisCode: 0.91,
        treatmentDetails: 0.95,
        claimAmount: 0.96,
        serviceDate: 0.94,
      },
    },
  };  